AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  kubernetes-aws-secrets
  
  Sample SAM Template for kubernetes-aws-secrets
Globals:
  Function:
    Timeout: 5

Parameters:
  SourceName:
    Type: String
    Default: "k8s.secrets"
    Description: "Name of the source to use in event source."
  ClusterId:
    Type: String
    Description: "EKS cluster ID"
  Region:
    Type: String
    Description: "EKS cluster region, default to current region"

Resources:
  KubernetesAwsSecrets:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: kubernetes-aws-secrets/
      Handler: main
      Runtime: go1.x
      Tracing: PassThrough
      MemorySize: 128
      Events:
        CatchAll:
          Type: CloudWatchEvent
          Properties:
            Pattern:
              source: [!Ref SourceName]
              detail:
                tags: [{ "Fn::Sub": [ "kubernetes.io/cluster/${Source}", { "Source": {"Ref" : "SourceName" }} ]}]
            InputPath: "$.detail.requestParameters.secretId"
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
                - secretsmanager:DescribeSecret
                - secretsmanager:ListSecretVersionIds
                - secretsmanager:ListSecrets
              Resource: '*'
            - Effect: Allow
              Action:
                - eks:DescribeCluster
                - eks:ListClusters
              Resource: '*'
      Environment:
        ClusterId: !Ref ClusterId
        Region: !Ref Region
